### ISSUE TITLE
Could not find actionbarsherlock.apk! Could not find PagerSlidingTabStripLib.apk!

### ISSUE THREAD

**Issue by alvarosantisteban** [balaji-k13/Navigation-drawer-page-sliding-tab-strip#5]
Hi, I followed the steps that you described in order to run the project, but I am receiving the following errors in the Console:
[2014-05-07 13:04:18 - actionbarsherlock] Could not find actionbarsherlock.apk!
[2014-05-07 13:04:18 - PagerSlidingTabStripLib] Could not find PagerSlidingTabStripLib.apk!

Then, if Im using a device with 2.3.6 the app crashes with the following trace:
05-07 13:08:08.132: E/AndroidRuntime(22508): FATAL EXCEPTION: main
05-07 13:08:08.132: E/AndroidRuntime(22508): android.view.InflateException: Binary XML file line #17: Error inflating class <unknown>
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.view.LayoutInflater.createView(LayoutInflater.java:518)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:332)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.ArrayAdapter.getView(ArrayAdapter.java:323)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.AbsListView.obtainView(AbsListView.java:1600)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.ListView.makeAndAddView(ListView.java:1764)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.ListView.fillDown(ListView.java:687)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.ListView.fillFromTop(ListView.java:744)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.ListView.layoutChildren(ListView.java:1615)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.AbsListView.onLayout(AbsListView.java:1430)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.view.View.layout(View.java:7228)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:767)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.view.View.layout(View.java:7228)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.view.View.layout(View.java:7228)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1254)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1130)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1047)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.view.View.layout(View.java:7228)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.view.View.layout(View.java:7228)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.view.View.layout(View.java:7228)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.view.ViewRoot.performTraversals(ViewRoot.java:1145)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.view.ViewRoot.handleMessage(ViewRoot.java:1865)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.os.Handler.dispatchMessage(Handler.java:99)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.os.Looper.loop(Looper.java:130)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.app.ActivityThread.main(ActivityThread.java:3687)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at java.lang.reflect.Method.invokeNative(Native Method)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at java.lang.reflect.Method.invoke(Method.java:507)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at dalvik.system.NativeStart.main(Native Method)
05-07 13:08:08.132: E/AndroidRuntime(22508): Caused by: java.lang.reflect.InvocationTargetException
05-07 13:08:08.132: E/AndroidRuntime(22508):    at java.lang.reflect.Constructor.constructNative(Native Method)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.view.LayoutInflater.createView(LayoutInflater.java:505)
05-07 13:08:08.132: E/AndroidRuntime(22508):    ... 35 more
05-07 13:08:08.132: E/AndroidRuntime(22508): Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x10102fd a=-1}
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.content.res.Resources.loadDrawable(Resources.java:1681)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.view.View.<init>(View.java:1961)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.TextView.<init>(TextView.java:383)
05-07 13:08:08.132: E/AndroidRuntime(22508):    at android.widget.TextView.<init>(TextView.java:376)
05-07 13:08:08.132: E/AndroidRuntime(22508):    ... 38 more

If I´m using a device with Android 4.4.2 it does not crash.

I think I´m installing the libs correctly, but I dont know anymore... :/

![bildschirmfoto 2014-05-07 um 13 14 58](https://cloud.githubusercontent.com/assets/951500/2901675/f6d38968-d5d8-11e3-8dab-346386727410.png)
![bildschirmfoto 2014-05-07 um 13 15 18](https://cloud.githubusercontent.com/assets/951500/2901676/f6d57106-d5d8-11e3-83f5-c82609e511a0.png)

**Comment by balaji-k13** [comment]
You need to clean and build the libraries first and after that clean and build main project to get rid of this kind of issues.

**Comment by Ejeus** [comment]
hi i have the same error issue as above, app works on higher versions of android but crashes on my android 2.3.6, any help or links would be greatly appreciated.
I even cleaned  and built all libraries and main project but nothing successful
